;*******************************************************************************
; PRACTICA 3 APARTADO B DE SISTEMAS BASADOS EN MICROPROCESADORES
; AUTORES: ALVARO SANCHEZ Y NICOLAS SERRANO
; PAREJA 10
;*******************************************************************************

DGROUP GROUP _DATA, _BSS				;; Se agrupan segmentos de datos en uno

_DATA SEGMENT WORD PUBLIC 'DATA' 		;; Segmento de datos DATA publico

_DATA ENDS

_BSS SEGMENT WORD PUBLIC 'BSS'			;; Segmento de datos BSS publico

_BSS ENDS

; DEFINICION DEL SEGMENTO DE CODIGO

_TEXT SEGMENT BYTE PUBLIC  'CODE'
    ASSUME CS:_TEXT

PUBLIC _createBarCode
_createBarCode PROC FAR

  PUSH BP ;GUARDAMOS EL CONTENIDO DE BP PARA LUEGO RECOGERLO

  MOV BP, SP

CONTROLD_W:
  MOV AL, [BP+14] ;GUARDAMOS EL CODIGO DE PRODUCTO
  LES BX, [BP+16]
  MOV ES:[BX+12], AL ;ESCRIBIMOS EL CODIGO DE PRODUCTO

INIP:
  MOV CX, 10000 ;COMENZAREMOS DIVIDIENDO EL NUMERO DE 5 CIFRAS ENTRE 10000
  ADD BX, 8
  MOV SI, 0
  MOV AX, [BP+10] ;LEEMOS LA PARTE BAJA DEL CODIGO DE PRODUCTO
  MOV DX, [BP+12] ;LEEMOS LA PARTE ALTA DEL CODIGO DE PRODUCTO
PRODUCTC_W: ;BUCLE PARA IR TRASNFORMANDO EL NÚMERO DE CINCO CIFRAS A ASCII
  DIV CX
  ADD AL, 48
  MOV ES:[BX], AL ;GUARDAMOS EN MEMORIA EL ENESIMO DIGITO
  CMP SI, 4 ;COMPRUEBA SI SE HA LEIDO EL ULTIMO ELEMENTO
  JE INIC
  PUSH DX
  MOV DX, 0
  MOV AX, CX
  MOV CX, 10 ;DECREMENTAMOS EL NUMERO QUE EMPLEAMOS PARA DIVIDIR DIVIDIENDOLO
             ;ENTRE 10
  DIV CX
  MOV CH, 0
  MOV CX, AX
  POP AX ;GUARDAMOS EL RESTO EN AX PARA SEGUIR DIVIDIENDOLO
  INC SI
  INC BX
  JMP PRODUCTC_W ;VUELTA AL COMIENZO DEL BUCLE

INIC:
  MOV CX, 1000 ;COMENZAREMOS DIVIDIENDO EL NUMERO DE 4 CIFRAS ENTRE 1000
  SUB BX, 8
  MOV SI, 0
  MOV AX, [BP+8] ;LEEMOS EL CODIGO DE EMPRESA
COMPANYC_W:
  DIV CX
  ADD AL, 48
  MOV ES:[BX], AL ;GUARDAMOS EN MEMORIA EL ENESIMO DIGITO
  CMP SI, 3 ;COMPRUEBA SI SE HA LEIDO EL ULTIMO ELEMENTO
  JE INICC
  PUSH DX ;GUARDAMOS EL RESTO EN LA PILA
  MOV DX, 0
  MOV AX, CX
  MOV CX, 10 ;DECREMENTAMOS EL NUMERO QUE EMPLEAMOS PARA DIVIDIR DIVIDIENDOLO
             ;ENTRE 10
  DIV CX
  MOV CH, 0
  MOV CX, AX
  POP AX ;GUARDAMOS EL RESTO EN AX PARA SEGUIR DIVIDIENDOLO
  INC SI
  INC BX
  JMP COMPANYC_W ;VUELTA AL COMIENZO DEL BUCLE

INICC:
  MOV CX, 100 ;COMENZAREMOS DIVIDIENDO EL NUMERO DE 3 CIFRAS ENTRE 100
  SUB BX, 6
  MOV SI, 0
  MOV AX, [BP+6] ;LEEMOS EL CODIGO DE EMPRESA
COUNTRYC_W:
  DIV CX
  ADD AL, 48
  MOV ES:[BX], AL ;GUARDAMOS EN MEMORIA EL ENESIMO DIGITO
  CMP SI, 2 ;COMPRUEBA SI SE HA LEIDO EL ULTIMO ELEMENTO
  JE FINB
  PUSH DX ;GUARDAMOS EL RESTO EN LA PILA
  MOV DX, 0
  MOV AX, CX
  MOV CX, 10 ;DECREMENTAMOS EL NUMERO QUE EMPLEAMOS PARA DIVIDIR DIVIDIENDOLO
             ;ENTRE 10
  DIV CX
  MOV CH, 0
  MOV CX, AX
  POP AX ;GUARDAMOS EL RESTO EN AX PARA SEGUIR DIVIDIENDOLO
  INC SI
  INC BX
  JMP COUNTRYC_W ;VUELTA AL COMIENZO DEL BUCLEMAKE CL

FINB:
  POP BP ;RECOGEMOS EL CONTENIDO DE BP
  RET

_createBarCode ENDP
_TEXT ENDS
END
