;*******************************************************************************
; PRACTICA 3 APARTADO A DE SISTEMAS BASADOS EN MICROPROCESADORES
; AUTORES: ALVARO SANCHEZ Y NICOLAS SERRANO
; PAREJA 10
;*******************************************************************************

DGROUP GROUP _DATA, _BSS				;; Se agrupan segmentos de datos en uno

_DATA SEGMENT WORD PUBLIC 'DATA' 		;; Segmento de datos DATA p�blico

  AUX DW ? ;LA EMPLEAREMOS PARA GUARDAR EN ELLA EL CONTENIDO DE ALGUN REGISTRO DE MANERA TEMPORAL

_DATA ENDS

_BSS SEGMENT WORD PUBLIC 'BSS'			;; Segmento de datos BSS p�blico

_BSS ENDS

; DEFINICION DEL SEGMENTO DE CODIGO

_TEXT SEGMENT BYTE PUBLIC  'CODE'
    ASSUME CS:_TEXT, DS:DGROUP, SS:DGROUP

PUBLIC _decodeBarCode
_decodeBarCode PROC FAR

  PUSH BP ;GUARDAMOS EL CONTENIDO DE BP PARA LUEGO RECOGERLO

  MOV BX, 12 ;DISTANCIA DESDE BP HASTA LA ULTIMA POSICION DEL ARRAY DEL ASCII
  MOV DX, BP
  SUB BP, BX
  MOV AX, 0

CONTROLDIGIT:
  MOV AL, [BP]
  SUB AL, 48
  PUSH BP
  ADD BP, 2
  MOV [BP], AX
  POP BP

PRODUCTCODE:
  MOV DX, 1 ;UTILIZAREMOS ESTE REGISTRO PARA IR MULTIPLICANDO POR EL DIGITO
  MOV CL, 10 ;POR CADA CICLO AL PASAR UN DIGITO A LA IZQUIERDA HAREMOS DX*=CL
  MOV AH, 0
  MOV BX, 0 ;GUARDAMOS EL VALOR DEL CODIGO DE PRODUCTO
  MOV SI, 0 ;CONTADOR QUE INDICA CUANTAS VECES SE HA REPETIDO EL BUCLE1
  PUSH BP
  DEC BP
BUCLE1: ;BUCLE PARA CALCULAR EL NÚMERO DEL CODIGO DE PRODUCTO
  MOV AH, 0
	MOV AL, [BP]
  SUB AL, 48
  MOV [AUX], DX
  MUL DX
  MOV DX, [AUX]
  ADD BX, AX
  MOV AX, DX
  MUL CL
  MOV DX, AX
	DEC BP
  CMP SI, 4
  JAE GUARDADOPC
  INC SI
  JMP BUCLE1

GUARDADOPC:
  POP BP
  MOV [BP+4], BX
  MOV [BP+6], WORD PTR 0


COMPANYCODE:
  MOV DX, 1 ;UTILIZAREMOS ESTE REGISTRO PARA IR MULTIPLICANDO POR EL DIGITO
  MOV CL, 10 ;POR CADA CICLO AL PASAR UN DIGITO A LA IZQUIERDA HAREMOS DX*=CL
  MOV AH, 0
  MOV BX, 0 ;GUARDAMOS EL VALOR DEL CODIGO DE PRODUCTO
  MOV SI, 0 ;CONTADOR QUE INDICA CUANTAS VECES SE HA REPETIDO EL BUCLE2
  PUSH BP
  SUB BP, 6
BUCLE2: ;BUCLE PARA CALCULAR EL NÚMERO DEL CODIGO DE EMPRESA
  MOV AH, 0
  MOV AL, [BP]
  SUB AL, 48
  MOV [AUX], DX
  MUL DX
  MOV DX, [AUX]
  ADD BX, AX
  MOV AX, DX
  MUL CL
  MOV DX, AX
  DEC BP
  CMP SI, 3
  JAE GUARDADOCC
  INC SI
  JMP BUCLE2

GUARDADOCC:
  POP BP
  MOV [BP+8], BX

COUNTRY_CODE:
  MOV DX, 1 ;UTILIZAREMOS ESTE REGISTRO PARA IR MULTIPLICANDO POR EL DIGITO
  MOV CL, 10 ;POR CADA CICLO AL PASAR UN DIGITO A LA IZQUIERDA HAREMOS DX*=CL
  MOV AH, 0
  MOV BX, 0 ;GUARDAMOS EL VALOR DEL CODIGO DE PRODUCTO
  MOV SI, 0 ;CONTADOR QUE INDICA CUANTAS VECES SE HA REPETIDO EL BUCLE3
  PUSH BP
  SUB BP, 10
BUCLE3: ;BUCLE PARA CALCULAR EL NÚMERO DEL CODIGO DE PAIS
  MOV AH, 0
  MOV AL, [BP]
  SUB AL, 48
  MOV [AUX], DX
  MUL DX
  MOV DX, [AUX]
  ADD BX, AX
  MOV AX, DX
  MUL CL
  MOV DX, AX
  DEC BP
  CMP SI, 2
  JAE GUARDADOCOUNTRYC
  INC SI
  JMP BUCLE3

GUARDADOCOUNTRYC:
  POP BP
  MOV [BP+10], BX

  POP BP

  RET

_decodeBarCode ENDP
_TEXT ENDS
END
