;_______________________________________________________________
; DEFINICION DEL SEGMENTO DE CODIGO
CODE SEGMENT
ASSUME CS:CODE
; COMIENZO DEL PROCEDIMIENTO (_computeControlDigit)
PUBLIC _computeControlDigit PROC FAR
	
	MOV BP, SP+4
	LES BX, [BP]
	
	;OBTENEMOS LOS 12 PRIMEROS DIGITOS DE EL CODIGO EN ASCII PASANDOLOS A DECIMAL Y LOS GUARDAMOS EN LA PILA
LECTURA:
	MOV AX, 0
	MOV DX, ES[BX]	;LOS CHAR SE EXTRAEN DE 2 EN 2
	SUB DH, 48	;CONVERSION NUMERO EN ASCII A HEX
	SUB DL, 48	;CONVERSION NUMERO EN ASCII A HEX
	PUSH DX	;GUARDAMOS LOS 2 NUMEROS CONVERTIDOS EN LA PILA
	INC BX	
	INC AX	
	CMP AX, 6
	JL LECTURA
	
	;SUMAMOS LOS VALORES DE LOS DIGITOS IMPARES
	MOV AX, 0
	POP DX
	
	

	
	
   
_computeControlDigit ENDP
	
	