;******************************************************************************* 
; PRACTICA 2 DE SISTEMAS BASADOS EN MICROPROCESADORES
; AUTORES: ALVARO SANCHEZ Y NICOLAS SERRANO
; PAREJA 10
;*******************************************************************************

; DEFINICION DEL SEGMENTO DE DATOS 

DATOS SEGMENT 

	MATRIZ DB 23, 4, 5, 3, 11, 18, 10, 6 , 9


DATOS ENDS 


; DEFINICION DEL SEGMENTO DE PILA 

PILA SEGMENT STACK "STACK" 
    DB   40H DUP (0) 
PILA ENDS 


; DEFINICION DEL SEGMENTO EXTRA 

EXTRA SEGMENT 
EXTRA ENDS 


; DEFINICION DEL SEGMENTO DE CODIGO 

CODE    SEGMENT 
    ASSUME CS:CODE, DS:DATOS, ES: EXTRA, SS:PILA 

; COMIENZO DEL PROCEDIMIENTO PRINCIPAL 

START PROC 
    ;INICIALIZA LOS REGISTROS DE SEGMENTO CON SUS VALORES 
    MOV AX, DATOS 
    MOV DS, AX 

    MOV AX, PILA 
    MOV SS, AX 

    MOV AX, EXTRA 
    MOV ES, AX 

	MOV SI, 0
	MOV BL, 100
	MOV BH, 0	

INI:
	MOV AX, 0
	MOV AL, MATRIZ[SI]	
	
ASCII:
	DIV BL
	CMP AL, 0
	JE DIV10
NUM:
	MOV BH, 1
	MOV CL, AH	;;GUARDAMOS EN CL EL RESTO, QUE SERA EL PROXIMO NUMERO A DIVIDIR
	ADD	AL, 48	;;ANADIMOS 48 PARA OBTENER EL ASCII DEL NUMERO EN CUESTION
	MOV DL, AL
	MOV AH, 2H	;;IMPRIMIMOS EL DIGITO
	INT 21H
	JMP DIV10	

CAMBIO: 
	MOV AL, CL
	JMP ASCII
	 


COMP:
	CMP AL, 0
	JE DIV10	
	JMP NUM
	
DIV10:
	MOV AX, 0
	MOV AL, BL
	MOV BL, 10
	DIV BL
	MOV BL, AL
	CMP BH, 1
	JE CAMBIO
	JMP INI
	


     ; FIN DEL PROGRAMA 
    MOV AX, 4C00H 
    INT 21H 


START ENDP 
; FIN DEL SEGMENTO DE CODIGO 
CODE ENDS 
; FIN DEL PROGRAMA INDICANDO DONDE COMIENZA LA EJECUCION 
END START 

